name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build ozhlathi-client
      working-directory: ./ozhlathi-client/
      run: cargo build --verbose
    - name: Build ozhlathi-web
      working-directory: ./ozhlathi-client/
      run: cargo build --verbose
